import { IPost } from '@/types';

export const postSliderSampleData: IPost[] = [
  {
    _id: '1',
    title: 'عرضه ویندوز 12 با هوش مصنوعی',
    briefText: 'ویندوز ۱۱ به‌لطف هوش مصنوعی قرار است تغییراتی قابل‌توجه به خود ببیند',
    type: 'free',
    author: {
      _id: '1',
      avatar: '',
      avatarUrl: '',
      name: 'علی اصغر',
    },
    category: {
      _id: '1',
      slug: '',
      title: 'تکنولوژی',
    },
    comments: [],
    commentsCount: 0,
    coverImageUrl: '',
    isBookmarked: false,
    isLiked: false,
    likesCount: 0,
    related: [],
    slug: '',
    tags: [],
    text: '',
    readingTime: 15,
    coverImage: '/assets/images/sample-1.png',
    createdAt: '2024-07-24T13:16:11.557+00:00',
    updatedAt: '2024-07-24T13:16:11.557+00:00',
  },
  {
    _id: '2',
    title: 'Call of Duty Warzone',
    briefText:
      'مانند دیگر بازی‌های بتل رویال سوار یک هواپیما خواهید شد و روی نقشه فرود خواهید آمد. وجه تفاوت این بازی نسبت به بقیه در تعداد بازیکنان آن است.',
    type: 'free',
    author: {
      _id: '1',
      avatar: '',
      avatarUrl: '',
      name: 'علی اصغر',
    },
    category: {
      _id: '1',
      slug: '',
      title: 'تکنولوژی',
    },
    comments: [],
    commentsCount: 0,
    coverImageUrl: '',
    isBookmarked: false,
    isLiked: false,
    likesCount: 0,
    related: [],
    slug: '',
    tags: [],
    text: '',
    readingTime: 3,
    coverImage: '/assets/images/sample-2.png',
    createdAt: '2024-07-24T13:16:11.557+00:00',
    updatedAt: '2024-07-24T13:16:11.557+00:00',
  },
];
