import type { Metadata } from 'next';
import '@/styles/globals.css';
import { vazirFont } from '@/constants/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
    >
      <body className={`${vazirFont.variable} font-sans antialiased`}>{children}</body>
    </html>
  );
}
