import type { Metadata } from 'next';
import 'swiper/css';
import 'swiper/css/navigation';
import '@/styles/globals.css';
import { vazirFont } from '@/constants/font';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
    >
      <body className={`${vazirFont.variable} font-sans antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
